"""Agent-facing ergonomics for the bounded WebMCP capability plane."""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from release_sentinel.interfaces.api import app
from release_sentinel.webmcp.contracts import TOOL_DEFINITIONS
from release_sentinel.webmcp.errors import WebMCPServiceError
from release_sentinel.webmcp.service import WebMCPChallengeService

ROOT = Path(__file__).parents[1]
client = TestClient(app)

CHAINED_TOOLS = {
    "find_counterexamples": "minimize_counterexample",
    "minimize_counterexample": "propose_remediation",
    "propose_remediation": "rebuild_candidate",
    "rebuild_candidate": "reverify_candidate",
}


def test_tool_descriptions_route_the_agent_through_the_repair_chain():
    descriptions = {tool.name: tool.description for tool in TOOL_DEFINITIONS}
    assert "START HERE" in descriptions["inspect_release"]
    for tool_name, successor in CHAINED_TOOLS.items():
        assert successor in descriptions[tool_name]


def test_service_error_serializes_a_concrete_recovery_action():
    error = WebMCPServiceError(
        "UNKNOWN_PROPOSAL",
        "proposal was not generated by this server",
        status_code=404,
        next_action="Call propose_remediation first.",
    )
    assert error.to_payload() == {
        "code": "UNKNOWN_PROPOSAL",
        "message": "proposal was not generated by this server",
        "next_action": "Call propose_remediation first.",
    }


def test_unknown_attack_api_names_a_valid_recovery_call():
    response = client.post("/v1/webmcp/attack/force_go")
    assert response.status_code == 422
    detail = response.json()["detail"]
    assert detail["code"] == "UNKNOWN_ATTACK"
    assert "force_agents_go" in detail["next_action"]


def test_out_of_order_remediation_calls_name_the_missing_predecessor():
    rebuild = client.post(
        "/v1/webmcp/remediation/rebuild",
        json={"proposal_id": "invented-by-agent", "proposal_digest": "0" * 64},
    )
    assert rebuild.status_code == 404
    assert "propose_remediation" in rebuild.json()["detail"]["next_action"]

    reverify = client.post(
        "/v1/webmcp/remediation/reverify",
        json={"candidate_id": "invented-by-agent", "new_source_sha256": "0" * 64},
    )
    assert reverify.status_code == 404
    assert "rebuild_candidate" in reverify.json()["detail"]["next_action"]


def test_unknown_proof_identity_names_supported_values():
    with pytest.raises(WebMCPServiceError) as caught:
        WebMCPChallengeService().verify_proof("demo-anything-else")
    next_action = caught.value.next_action or ""
    assert "demo-current" in next_action
    assert "demo-cross-tenant-fixed" in next_action
    assert "demo-path-traversal-fixed" in next_action
    assert "demo-evidence-tamper-fixed" in next_action


def test_browser_surfaces_next_action_in_tool_errors():
    arena = (ROOT / "src/release_sentinel/interfaces/static/arena.js").read_text(encoding="utf-8")
    assert "detail?.next_action" in arena
    assert "error.nextAction" in arena
