from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any

from release_sentinel.coverage.canonical import sha256_json
from release_sentinel.operations.attestation import build_evidence_bundle, demo_signer_from_env, sign_evidence_bundle
from release_sentinel.release.gatekeeper import A2AGatekeeperClient, gatekeeper_from_env
from release_sentinel.webmcp.demo_runtime import evaluate_fixture, fixture_source_sha
from release_sentinel.webmcp.demo_scenarios import DemoReleaseId, get_scenario, supported_release_ids
from release_sentinel.webmcp.errors import WebMCPServiceError


@dataclass(frozen=True)
class ProposalRecord:
    proposal_id: str
    demo_release_id: str
    base_source_sha256: str
    target_source_sha256: str
    fixed_fixture: str
    fixed_proof_id: str
    proposal_digest: str


@dataclass(frozen=True)
class CandidateRecord:
    candidate_id: str
    proposal_id: str
    demo_release_id: str
    old_source_sha256: str
    new_source_sha256: str
    fixture_name: str
    proof_id: str


class RemediationAdapter:
    def __init__(self) -> None:
        self._proposals: dict[str, ProposalRecord] = {}
        self._candidates: dict[str, CandidateRecord] = {}

    def propose_remediation(self, demo_release_id: str = DemoReleaseId.CROSS_TENANT.value) -> dict[str, Any]:
        try:
            scenario = get_scenario(demo_release_id)
        except KeyError as exc:
            allowed = ", ".join(supported_release_ids())
            raise WebMCPServiceError(
                "UNKNOWN_DEMO_RELEASE",
                "demo release is not in the package-owned remediation allowlist",
                status_code=404,
                next_action=f"Call propose_remediation with one of: {allowed}.",
            ) from exc

        release_id = scenario.release_id.value
        base_sha = fixture_source_sha(scenario.vulnerable_fixture)
        target_sha = fixture_source_sha(scenario.fixed_fixture)
        payload = {
            "demo_release_id": release_id,
            "base_source_sha256": base_sha,
            "target_source_sha256": target_sha,
            "fixed_fixture": scenario.fixed_fixture,
            "fixed_proof_id": scenario.fixed_proof_id.value,
            "allowed_paths": ["app.py"],
            "producer": "release-sentinel-server-owned-demo-remediation",
            "authority": "PROPOSAL_ONLY",
        }
        digest = sha256_json(payload)
        proposal_id = "proposal-" + digest[:20]
        self._proposals[proposal_id] = ProposalRecord(
            proposal_id=proposal_id,
            demo_release_id=release_id,
            base_source_sha256=base_sha,
            target_source_sha256=target_sha,
            fixed_fixture=scenario.fixed_fixture,
            fixed_proof_id=scenario.fixed_proof_id.value,
            proposal_digest=digest,
        )
        return {
            "proposal_id": proposal_id,
            "demo_release_id": release_id,
            "scenario_label": scenario.label,
            "base_source_sha256": base_sha,
            "target_source_sha256": target_sha,
            "allowed_change_summary": (
                f"Replace only app.py with the package-owned fixed fixture for {scenario.label}."
            ),
            "proposal_digest": digest,
            "authority": "PROPOSAL_ONLY",
            "approved": False,
        }

    def rebuild_candidate(self, proposal_id: str, proposal_digest: str) -> dict[str, Any]:
        proposal = self._proposals.get(proposal_id)
        if proposal is None:
            raise WebMCPServiceError(
                "UNKNOWN_PROPOSAL",
                "proposal was not generated by this server",
                status_code=404,
                next_action=(
                    "Call propose_remediation first and pass the proposal_id it returns. "
                    "Proposal identifiers cannot be invented by the caller."
                ),
            )
        if proposal.proposal_digest != proposal_digest:
            raise WebMCPServiceError(
                "PROPOSAL_DIGEST_MISMATCH",
                "proposal digest does not match server record",
                next_action="Pass proposal_digest exactly as returned by propose_remediation.",
            )
        actual_target_sha = fixture_source_sha(proposal.fixed_fixture)
        if actual_target_sha != proposal.target_source_sha256:
            raise WebMCPServiceError("TARGET_FIXTURE_MISMATCH", "package-owned fixed fixture changed unexpectedly")

        candidate_payload = {
            "proposal_id": proposal.proposal_id,
            "demo_release_id": proposal.demo_release_id,
            "old_source_sha256": proposal.base_source_sha256,
            "new_source_sha256": proposal.target_source_sha256,
            "fixture": proposal.fixed_fixture,
            "proof_id": proposal.fixed_proof_id,
        }
        candidate_id = "candidate-" + sha256_json(candidate_payload)[:20]
        self._candidates[candidate_id] = CandidateRecord(
            candidate_id=candidate_id,
            proposal_id=proposal.proposal_id,
            demo_release_id=proposal.demo_release_id,
            old_source_sha256=proposal.base_source_sha256,
            new_source_sha256=proposal.target_source_sha256,
            fixture_name=proposal.fixed_fixture,
            proof_id=proposal.fixed_proof_id,
        )
        return {
            "candidate_id": candidate_id,
            "proposal_id": proposal.proposal_id,
            "demo_release_id": proposal.demo_release_id,
            "old_source_sha256": proposal.base_source_sha256,
            "new_source_sha256": proposal.target_source_sha256,
            "build_status": "REBUILT_FROM_PACKAGE_OWNED_FIXTURE",
            "verdict": "NOT_YET_REVERIFIED",
            "inherited_verdict": False,
            "webmcp_authority": "NO_RELEASE_AUTHORITY",
        }

    def reverify_candidate(self, candidate_id: str, new_source_sha256: str) -> dict[str, Any]:
        candidate = self._candidates.get(candidate_id)
        if candidate is None:
            raise WebMCPServiceError(
                "UNKNOWN_CANDIDATE",
                "candidate was not generated by this server",
                status_code=404,
                next_action="Call rebuild_candidate first and pass the candidate_id it returns.",
            )
        if candidate.new_source_sha256 != new_source_sha256:
            raise WebMCPServiceError(
                "SOURCE_CONTEXT_MISMATCH",
                "candidate source hash does not match rebuild context",
                next_action="Pass new_source_sha256 exactly as returned by rebuild_candidate.",
            )

        report, actual_sha = evaluate_fixture(candidate.fixture_name, release_id=f"webmcp-{candidate_id}-reverify")
        if actual_sha != candidate.new_source_sha256:
            raise WebMCPServiceError(
                "SOURCE_CONTEXT_MISMATCH", "fresh evaluation source hash differs from candidate context"
            )

        authority = "DETERMINISTIC_GATEKEEPER"
        verdict = report.decision.value
        gatekeeper = report.to_dict()["gatekeeper"]
        if os.getenv("RELEASE_SENTINEL_WEBMCP_JUDGED_MODE", "").strip() == "1":
            signed = sign_evidence_bundle(
                build_evidence_bundle(report, source_sha256=actual_sha),
                demo_signer_from_env(),
            )
            try:
                remote = gatekeeper_from_env(require_remote=True)
                if not isinstance(remote, A2AGatekeeperClient):
                    raise RuntimeError("remote Gatekeeper required")
                remote_verdict = remote.decide_attested(
                    release_id=report.release_id,
                    source_sha256=actual_sha,
                    policy_sha256=report.policy_sha256,
                    signed_evidence_bundle=signed,
                    agent_opinions=[],
                )
            except Exception as exc:
                raise WebMCPServiceError(
                    "GATEKEEPER_DEPENDENCY_UNAVAILABLE",
                    f"judged-mode re-verification failed closed: {type(exc).__name__}",
                    status_code=503,
                    next_action=(
                        "The candidate remains unapproved. Retry reverify_candidate with the same "
                        "candidate_id and new_source_sha256 once the Gatekeeper is reachable."
                    ),
                ) from exc
            verdict = remote_verdict.decision.value
            gatekeeper = remote_verdict.to_dict()
            authority = "DETERMINISTIC_GO_GATEKEEPER"

        return {
            "candidate_id": candidate_id,
            "demo_release_id": candidate.demo_release_id,
            "proof_id": candidate.proof_id,
            "source_sha256": actual_sha,
            "fresh_evidence_sha256": report.evidence_sha256,
            "fresh_evaluation": True,
            "final_verdict": verdict,
            "authority": authority,
            "gatekeeper": gatekeeper,
            "webmcp_authority": "NO_RELEASE_AUTHORITY",
        }
